name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle & Build APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-home-cache-cleanup: true
          cache-overwrite-existing: true
          cache-read-only: false
          arguments: publish
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: repo
      - run: ls repo
